# Generated by Django 4.2.2 on 2023-06-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('video', models.FileField(upload_to='video')),
                ('user_uuid', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fb_url', models.URLField()),
                ('wa_url', models.URLField()),
                ('tel_url', models.URLField()),
            ],
        ),
    ]
