# Generated by Django 4.2.2 on 2023-07-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='ends',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='starts',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='texts',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
